### ISSUE TITLE
When ./RunGame is run in terminal, the game does not run

### ISSUE THREAD

**Issue by jolkin** [Kyle-Helmick/Helmick_Stevenson_CSCI2270_FinalProject#1]
The terminal says that there is no such file or directory. And, when I try to run RunGame from Finder when, the terminal says it cannot run a binary file. I have also tried to compile the code on my own, but the terminal says that Printing.h is missing.

**Comment by Kyle-Helmick** [comment]
Pushed make file. As mentioned in comment usage of make file is documented in updated README.md.
